name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm ci

      - name: Instalar Allure CLI
        run: npm install -g allure-commandline

      - name: Executar Cypress com Allure
        run: npx cypress run --env allure=true

      - name: Gerar relatório Allure
        run: npx allure generate allure-results --clean -o allure-report

      - name: Salvar relatório Allure como artefato
  uses: actions/upload-artifact@v3
  with:
    name: allure-report
    path: allure-report
